apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{ include "phalanx.namespace" . }}
  labels:
    {{- include "phalanx.labels" . | nindent 4 }}
data:
  gitlab-group: {{ .Values.gitlab.group | default "" | quote }}
{{- if .Values.customCACerts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phalanx-ca-certs
  namespace: {{ include "phalanx.namespace" . }}
  labels:
    {{- include "phalanx.labels" . | nindent 4 }}
data:
  ca-bundle.crt: |
    {{- .Values.customCACerts | nindent 4 }}
{{- end }}
